name: Argos CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      # Those 3 are the default PR workflow activity types,
      # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - synchronize
      - reopened
      # We want trigger workflow on labeled too!
      - labeled

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

            - name: Build the website
        run: yarn docusaurus build

      - name: Take screenshots with Playwright
        run: yarn playwright test

      - name: Upload screenshots to Argos
        run: yarn argos upload ./screenshots

      - name: Take Argos screenshots
            run: yarn argos upload ./screenshots

      - name: Take Argos screenshots
        run: yarn argos:screenshot
